server:
  port: 8090
  servlet:
    context-path: /postgresdemo
spring:
  profiles:
    active: dev
    #datasource:
    #filters: stat,wall,log4j

    ## 初始化大小，最小，最大
    #initialSize: 5
    #minIdle: 5
    #maxActive: 20

    ## 配置获取连接等待超时的时间
    #maxWait: 60000

    ## 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    #timeBetweenEvictionRunsMillis: 60000

    ## 配置一个连接在池中最小生存的时间，单位是毫秒
    #minEvictableIdleTimeMillis: 300000

    ## 校验SQL SELECT 1 FROM DUAL，如果不配validationQuery项，则下面三项配置无用
    #validationQuery: SELECT 1 FROM DUAL
    #testWhileIdle: true
    #testOnBorrow: false
    #testOnReturn: false

    ## 合并多个DruidDataSource的监控数据
    #useGlobalDataSourceStat: true

druid:
  monitor:
    username: adminll
    password: admin
    allow: 10.0.4.198,10.0.5.164
mybatis:
  mapper-locations: classpath:mybatis/*.xml

logging:
  config: classpath:config/logback.groovy
